// API配置

const CURRENT_LOCATION = window.location;
const CURRENT_PROTOCOL = CURRENT_LOCATION.protocol;
const CURRENT_HOST = CURRENT_LOCATION.hostname;
//const CURRENT_PORT = CURRENT_LOCATION.port
const CURRENT_PORT = "3000";

const BASE_URL = `${CURRENT_PROTOCOL}//${CURRENT_HOST}:${CURRENT_PORT}`;
const API_URL = `${BASE_URL}/api`;

export { BASE_URL, API_URL };
